modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
issueTrackerURL="https://github.com/daedalus4096/PrimalMagick/issues"
license="${license}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
updateJSONURL="https://pastebin.com/raw/MZu4yZi8"
displayURL="https://www.curseforge.com/minecraft/mc-mods/primal-magick"
logoFile="primalmagick_banner_small.png"
credits="${credits}"
authors="Daedalus4096"
description='''${description}'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="verdantcore"
mandatory=true
versionRange="[${verdantcore_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="commonnetworking"
mandatory=true
versionRange="[${common_network_version},)"
ordering="NONE"
side="BOTH"
