package com.verdantartifice.primalmagick.test;

import com.verdantartifice.primalmagick.common.blocks.BlocksPM;
import com.verdantartifice.primalmagick.common.damagesource.DamageSourcesPM;
import com.verdantartifice.primalmagick.common.registries.IRegistryItem;
import com.verdantartifice.primalmagick.common.sources.Sources;
import com.verdantartifice.primalmagick.platform.Services;
import com.verdantartifice.primalmagick.test.attunements.AttunementTests;
import com.verdantartifice.primalmagick.test.capabilities.AbstractPlayerKnowledgeTest;
import com.verdantartifice.primalmagick.test.capabilities.ItemHandlerTests;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.world.damagesource.DamageSources;

import java.util.function.Consumer;

public class TestFunctionsPM {
    public static void init() {
        // Pass the service initialization through this class so it gets class loaded and fields registered
        Services.TEST_FUNCTIONS_REGISTRY.init();
    }

    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> CANARY = Services.TEST_FUNCTIONS_REGISTRY.register("canary", () -> CanaryTest::canary);

    // Attunement buff tests
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MINOR_ATTUNEMENT_DISCOUNT_EARTH = Services.TEST_FUNCTIONS_REGISTRY.register("minor_attunement_gives_mana_discount_earth", () -> (helper) -> AttunementTests.minor_attunement_gives_mana_discount(helper, Sources.EARTH));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MINOR_ATTUNEMENT_DISCOUNT_SEA = Services.TEST_FUNCTIONS_REGISTRY.register("minor_attunement_gives_mana_discount_sea", () -> (helper) -> AttunementTests.minor_attunement_gives_mana_discount(helper, Sources.SEA));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MINOR_ATTUNEMENT_DISCOUNT_SKY = Services.TEST_FUNCTIONS_REGISTRY.register("minor_attunement_gives_mana_discount_sky", () -> (helper) -> AttunementTests.minor_attunement_gives_mana_discount(helper, Sources.SKY));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MINOR_ATTUNEMENT_DISCOUNT_SUN = Services.TEST_FUNCTIONS_REGISTRY.register("minor_attunement_gives_mana_discount_sun", () -> (helper) -> AttunementTests.minor_attunement_gives_mana_discount(helper, Sources.SUN));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MINOR_ATTUNEMENT_DISCOUNT_MOON = Services.TEST_FUNCTIONS_REGISTRY.register("minor_attunement_gives_mana_discount_moon", () -> (helper) -> AttunementTests.minor_attunement_gives_mana_discount(helper, Sources.MOON));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MINOR_ATTUNEMENT_DISCOUNT_BLOOD = Services.TEST_FUNCTIONS_REGISTRY.register("minor_attunement_gives_mana_discount_blood", () -> (helper) -> AttunementTests.minor_attunement_gives_mana_discount(helper, Sources.BLOOD));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MINOR_ATTUNEMENT_DISCOUNT_INFERNAL = Services.TEST_FUNCTIONS_REGISTRY.register("minor_attunement_gives_mana_discount_infernal", () -> (helper) -> AttunementTests.minor_attunement_gives_mana_discount(helper, Sources.INFERNAL));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MINOR_ATTUNEMENT_DISCOUNT_VOID = Services.TEST_FUNCTIONS_REGISTRY.register("minor_attunement_gives_mana_discount_void", () -> (helper) -> AttunementTests.minor_attunement_gives_mana_discount(helper, Sources.VOID));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> MINOR_ATTUNEMENT_DISCOUNT_HALLOWED = Services.TEST_FUNCTIONS_REGISTRY.register("minor_attunement_gives_mana_discount_hallowed", () -> (helper) -> AttunementTests.minor_attunement_gives_mana_discount(helper, Sources.HALLOWED));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> LESSER_EARTH_ATTUNEMENT_BUFF = Services.TEST_FUNCTIONS_REGISTRY.register("lesser_earth_attunement_gives_haste_modifier", () -> AttunementTests::lesser_earth_attunement_gives_haste_modifier);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GREATER_EARTH_ATTUNEMENT_BUFF = Services.TEST_FUNCTIONS_REGISTRY.register("greater_earth_attunement_gives_step_height_modifier", () -> AttunementTests::greater_earth_attunement_gives_step_height_modifier);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> LESSER_SEA_ATTUNEMENT_BUFF = Services.TEST_FUNCTIONS_REGISTRY.register("lesser_sea_attunement_gives_increased_swim_speed", () -> AttunementTests::lesser_sea_attunement_gives_increased_swim_speed);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GREATER_SEA_ATTUNEMENT_BUFF = Services.TEST_FUNCTIONS_REGISTRY.register("greater_sea_attunement_gives_water_breathing", () -> AttunementTests::greater_sea_attunement_gives_water_breathing);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> LESSER_SKY_ATTUNEMENT_BUFF1 = Services.TEST_FUNCTIONS_REGISTRY.register("lesser_sky_attunement_gives_movement_speed_modifier", () -> AttunementTests::lesser_sky_attunement_gives_movement_speed_modifier);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> LESSER_SKY_ATTUNEMENT_BUFF2 = Services.TEST_FUNCTIONS_REGISTRY.register("lesser_sky_attunement_reduces_fall_damage_taken", () -> AttunementTests::lesser_sky_attunement_reduces_fall_damage_taken);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GREATER_SKY_ATTUNEMENT_BUFF = Services.TEST_FUNCTIONS_REGISTRY.register("greater_sky_attunement_increases_jump_strength", () -> AttunementTests::greater_sky_attunement_increases_jump_strength);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> LESSER_SUN_ATTUNEMENT_DAY_BUFF = Services.TEST_FUNCTIONS_REGISTRY.register("lesser_sun_attunement_regenerates_food_during_day", () -> AttunementTests::lesser_sun_attunement_regenerates_food_during_day);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> LESSER_SUN_ATTUNEMENT_NIGHT_BUFF = Services.TEST_FUNCTIONS_REGISTRY.register("lesser_sun_attunement_does_not_regenerate_food_during_night", () -> AttunementTests::lesser_sun_attunement_does_not_regenerate_food_during_night);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> LESSER_MOON_ATTUNEMENT_BUFF = Services.TEST_FUNCTIONS_REGISTRY.register("lesser_moon_attunement_grants_invisibility_chance_on_hurt", () -> AttunementTests::lesser_moon_attunement_grants_invisibility_chance_on_hurt);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GREATER_MOON_ATTUNEMENT_BUFF = Services.TEST_FUNCTIONS_REGISTRY.register("greater_moon_attunement_grants_night_vision", () -> AttunementTests::greater_moon_attunement_grants_night_vision);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> LESSER_BLOOD_ATTUNEMENT_BUFF = Services.TEST_FUNCTIONS_REGISTRY.register("lesser_blood_attunement_inflicts_bleeding", () -> AttunementTests::lesser_blood_attunement_inflicts_bleeding);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GREATER_BLOOD_ATTUNEMENT_BUFF = Services.TEST_FUNCTIONS_REGISTRY.register("greater_blood_attunement_grants_chance_at_self_healing", () -> AttunementTests::greater_blood_attunement_grants_chance_at_self_healing);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GREATER_INFERNAL_ATTUNEMENT_BUFF_IN_FIRE = Services.TEST_FUNCTIONS_REGISTRY.register("greater_infernal_attunement_prevents_fire_damage_in_fire", () -> (helper) -> AttunementTests.greater_infernal_attunement_prevents_fire_damage(helper, registryAccess -> new DamageSources(registryAccess).inFire()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GREATER_INFERNAL_ATTUNEMENT_BUFF_ON_FIRE = Services.TEST_FUNCTIONS_REGISTRY.register("greater_infernal_attunement_prevents_fire_damage_on_fire", () -> (helper) -> AttunementTests.greater_infernal_attunement_prevents_fire_damage(helper, registryAccess -> new DamageSources(registryAccess).onFire()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GREATER_INFERNAL_ATTUNEMENT_BUFF_LAVA = Services.TEST_FUNCTIONS_REGISTRY.register("greater_infernal_attunement_prevents_fire_damage_lava", () -> (helper) -> AttunementTests.greater_infernal_attunement_prevents_fire_damage(helper, registryAccess -> new DamageSources(registryAccess).lava()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GREATER_INFERNAL_ATTUNEMENT_BUFF_HOT_FLOOR = Services.TEST_FUNCTIONS_REGISTRY.register("greater_infernal_attunement_prevents_fire_damage_hot_floor", () -> (helper) -> AttunementTests.greater_infernal_attunement_prevents_fire_damage(helper, registryAccess -> new DamageSources(registryAccess).hotFloor()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GREATER_INFERNAL_ATTUNEMENT_BUFF_INFERNAL_SORCERY = Services.TEST_FUNCTIONS_REGISTRY.register("greater_infernal_attunement_prevents_fire_damage_infernal_sorcery", () -> (helper) -> AttunementTests.greater_infernal_attunement_prevents_fire_damage(helper, registryAccess -> DamageSourcesPM.sorcery(registryAccess, Sources.INFERNAL, null)));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> LESSER_VOID_ATTUNEMENT_BUFF = Services.TEST_FUNCTIONS_REGISTRY.register("lesser_void_attunement_reduces_damage_taken", () -> AttunementTests::lesser_void_attunement_reduces_damage_taken);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GREATER_VOID_ATTUNEMENT_BUFF = Services.TEST_FUNCTIONS_REGISTRY.register("greater_void_attunement_increases_damage_dealt", () -> AttunementTests::greater_void_attunement_increases_damage_dealt);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> LESSER_HALLOWED_ATTUNEMENT_BUFF = Services.TEST_FUNCTIONS_REGISTRY.register("lesser_hallowed_attunement_doubles_damage_dealt_to_undead", () -> AttunementTests::lesser_hallowed_attunement_doubles_damage_dealt_to_undead);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GREATER_HALLOWED_ATTUNEMENT_BUFF = Services.TEST_FUNCTIONS_REGISTRY.register("greater_hallowed_attunement_prevents_death", () -> AttunementTests::greater_hallowed_attunement_prevents_death);

    // Item handler tests
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> ITEM_HANDLER_NULL_DIRECTION_RESEARCH_TABLE = Services.TEST_FUNCTIONS_REGISTRY.register("block_entity_can_retrieve_item_handler_with_null_direction_research_table", () -> (helper) -> ItemHandlerTests.block_entity_can_retrieve_item_handler_with_null_direction(helper, BlocksPM.RESEARCH_TABLE.get()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> ITEM_HANDLER_NULL_DIRECTION_WAND_CHARGER = Services.TEST_FUNCTIONS_REGISTRY.register("block_entity_can_retrieve_item_handler_with_null_direction_wand_charger", () -> (helper) -> ItemHandlerTests.block_entity_can_retrieve_item_handler_with_null_direction(helper, BlocksPM.WAND_CHARGER.get()));
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> ITEM_HANDLER_NULL_DIRECTION_CALCINATOR_BASIC = Services.TEST_FUNCTIONS_REGISTRY.register("block_entity_can_retrieve_item_handler_with_null_direction_calcinator_basic", () -> (helper) -> ItemHandlerTests.block_entity_can_retrieve_item_handler_with_null_direction(helper, BlocksPM.CALCINATOR_BASIC.get()));

    // Player knowledge tests
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> ADD_AND_CHECK_RESEARCH = Services.TEST_FUNCTIONS_REGISTRY.register("player_knowledge_add_and_check_research", () -> AbstractPlayerKnowledgeTest::player_knowledge_add_and_check_research);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> CANNOT_ADD_DUPLICATE_RESEARCH = Services.TEST_FUNCTIONS_REGISTRY.register("player_knowledge_cannot_add_duplicate_research", () -> AbstractPlayerKnowledgeTest::player_knowledge_cannot_add_duplicate_research);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> REMOVE_RESEARCH = Services.TEST_FUNCTIONS_REGISTRY.register("player_knowledge_remove_research", () -> AbstractPlayerKnowledgeTest::player_knowledge_remove_research);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GET_RESEARCH_SET = Services.TEST_FUNCTIONS_REGISTRY.register("player_knowledge_get_research_set", () -> AbstractPlayerKnowledgeTest::player_knowledge_get_research_set);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GET_SET_RESEARCH_STAGE = Services.TEST_FUNCTIONS_REGISTRY.register("player_knowledge_get_set_research_stage", () -> AbstractPlayerKnowledgeTest::player_knowledge_get_set_research_stage);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GET_SET_RESEARCH_FLAG = Services.TEST_FUNCTIONS_REGISTRY.register("player_knowledge_get_set_research_flag", () -> AbstractPlayerKnowledgeTest::player_knowledge_get_set_research_flag);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> REMOVE_RESEARCH_FLAG = Services.TEST_FUNCTIONS_REGISTRY.register("player_knowledge_remove_research_flag", () -> AbstractPlayerKnowledgeTest::player_knowledge_remove_research_flag);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GET_RESEARCH_FLAGS = Services.TEST_FUNCTIONS_REGISTRY.register("player_knowledge_get_research_flags", () -> AbstractPlayerKnowledgeTest::player_knowledge_get_research_flags);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GET_RESEARCH_STATUS = Services.TEST_FUNCTIONS_REGISTRY.register("player_knowledge_get_research_status", () -> AbstractPlayerKnowledgeTest::player_knowledge_get_research_status);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> IS_RESEARCH_COMPLETE = Services.TEST_FUNCTIONS_REGISTRY.register("player_knowledge_is_research_complete", () -> AbstractPlayerKnowledgeTest::player_knowledge_is_research_complete);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GET_SET_KNOWLEDGE_RAW = Services.TEST_FUNCTIONS_REGISTRY.register("player_knowledge_get_set_knowledge_raw", () -> AbstractPlayerKnowledgeTest::player_knowledge_get_set_knowledge_raw);
    public static final IRegistryItem<Consumer<GameTestHelper>, Consumer<GameTestHelper>> GET_KNOWLEDGE_LEVELS = Services.TEST_FUNCTIONS_REGISTRY.register("player_knowledge_get_knowledge_levels", () -> AbstractPlayerKnowledgeTest::player_knowledge_get_knowledge_levels);

}
