package com.verdantartifice.primalmagick.datagen.theorycrafting;

import java.nio.file.Path;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.util.function.Consumer;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.google.common.collect.ImmutableList;
import com.verdantartifice.primalmagick.PrimalMagick;
import com.verdantartifice.primalmagick.common.blocks.BlocksPM;
import com.verdantartifice.primalmagick.common.items.ItemsPM;
import com.verdantartifice.primalmagick.common.research.CompoundResearchKey;
import com.verdantartifice.primalmagick.common.research.QuorumResearchKey;
import com.verdantartifice.primalmagick.common.research.ResearchNames;
import com.verdantartifice.primalmagick.common.research.SimpleResearchKey;
import com.verdantartifice.primalmagick.common.sources.Source;
import com.verdantartifice.primalmagick.common.tags.ItemTagsForgeExt;
import com.verdantartifice.primalmagick.common.tags.ItemTagsPM;

import net.minecraft.data.CachedOutput;
import net.minecraft.data.DataProvider;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.ItemTags;
import net.minecraft.world.entity.raid.Raid;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.alchemy.PotionUtils;
import net.minecraft.world.item.alchemy.Potions;
import net.minecraft.world.level.block.Blocks;
import net.minecraftforge.common.Tags;

public class ProjectProvider implements DataProvider {
    private static final Logger LOGGER = LogManager.getLogger();
    protected final PackOutput packOutput;
    
    public ProjectProvider(PackOutput packOutput) {
        this.packOutput = packOutput;
    }

    @Override
    public CompletableFuture<?> run(CachedOutput cache) {
        ImmutableList.Builder<CompletableFuture<?>> futuresBuilder = new ImmutableList.Builder<>();
        Map<ResourceLocation, IFinishedProject> map = new HashMap<>();
        this.registerProjects((project) -> {
            if (map.put(project.getId(), project) != null) {
                LOGGER.debug("Duplicate theorycrafting project in data generation: {}", project.getId().toString());
            }
        });
        map.entrySet().forEach(entry -> {
            futuresBuilder.add(DataProvider.saveStable(cache, entry.getValue().getProjectJson(), this.getPath(this.packOutput, entry.getKey())));
        });
        return CompletableFuture.allOf(futuresBuilder.build().toArray(CompletableFuture[]::new));
    }

    private Path getPath(PackOutput output, ResourceLocation entryLoc) {
        return output.getOutputFolder(PackOutput.Target.DATA_PACK).resolve(entryLoc.getNamespace()).resolve("theorycrafting").resolve(entryLoc.getPath() + ".json");
    }
    
    protected void registerProjects(Consumer<IFinishedProject> consumer) {
        SimpleResearchKey shardSynthesis = ResearchNames.SHARD_SYNTHESIS.get().simpleKey();
        
        ProjectBuilder.project("advanced_enchanting_studies").rewardMultiplier(0.5D).requiredResearch(CompoundResearchKey.from(true, "EXPERT_MANAWEAVING", "PRIMALITE"))
            .weightFunction(ProgressiveWeightFunctionBuilder.start(5).modifier("MASTER_MANAWEAVING", -1).modifier("SUPREME_MANAWEAVING", -1).build())
            .material(ItemTagMaterialBuilder.tag(ItemTagsPM.ENCHANTING_TABLES, false).weight(5).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.GEMS_LAPIS, 2, true).weight(5).build())
            .material(ExperienceMaterialBuilder.experience(2, true).bonusReward(0.25D).weight(5).build())
            .material(ItemMaterialBuilder.item(Items.BOOK, false).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.PRIMALITE_SWORD.get(), false).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.PRIMALITE_PICKAXE.get(), false).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.PRIMALITE_SHOVEL.get(), false).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.PRIMALITE_AXE.get(), false).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.PRIMALITE_HOE.get(), false).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.PRIMALITE_HEAD.get(), false).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.PRIMALITE_CHEST.get(), false).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.PRIMALITE_LEGS.get(), false).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.PRIMALITE_FEET.get(), false).weight(1).build())
            .material(ObservationMaterialBuilder.observation(1, true).weight(5).build())
            .build(consumer);
        ProjectBuilder.project("advanced_essence_analysis").requiredResearch("CRYSTAL_SYNTHESIS").rewardMultiplier(0.5D)
            .weightFunction(ProgressiveWeightFunctionBuilder.start(5).modifier("CLUSTER_SYNTHESIS", -2).build())
            .material(ObservationMaterialBuilder.observation(1, true).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_SHARD_EARTH.get(), true).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_SHARD_SEA.get(), true).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_SHARD_SKY.get(), true).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_SHARD_SUN.get(), true).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_SHARD_MOON.get(), true).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_SHARD_BLOOD.get(), true).requiredResearch(Source.BLOOD.getDiscoverKey()).afterCrafting(5).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_SHARD_INFERNAL.get(), true).requiredResearch(Source.INFERNAL.getDiscoverKey()).afterCrafting(5).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_SHARD_VOID.get(), true).requiredResearch(Source.VOID.getDiscoverKey()).afterCrafting(5).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_SHARD_HALLOWED.get(), true).requiredResearch(Source.HALLOWED.getDiscoverKey()).afterCrafting(5).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CRYSTAL_EARTH.get(), true).afterCrafting(5).bonusReward(0.25D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CRYSTAL_SEA.get(), true).afterCrafting(5).bonusReward(0.25D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CRYSTAL_SKY.get(), true).afterCrafting(5).bonusReward(0.25D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CRYSTAL_SUN.get(), true).afterCrafting(5).bonusReward(0.25D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CRYSTAL_MOON.get(), true).afterCrafting(5).bonusReward(0.25D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CRYSTAL_BLOOD.get(), true).requiredResearch(Source.BLOOD.getDiscoverKey()).afterCrafting(5).bonusReward(0.25D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CRYSTAL_INFERNAL.get(), true).requiredResearch(Source.INFERNAL.getDiscoverKey()).afterCrafting(5).bonusReward(0.25D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CRYSTAL_VOID.get(), true).requiredResearch(Source.VOID.getDiscoverKey()).afterCrafting(5).bonusReward(0.25D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CRYSTAL_HALLOWED.get(), true).requiredResearch(Source.HALLOWED.getDiscoverKey()).afterCrafting(5).bonusReward(0.25D).weight(1).build())
            .build(consumer);
        ProjectBuilder.project("advanced_ritual_practice").rewardMultiplier(0.5D).requiredResearch(QuorumResearchKey.builder(2).add("RITUAL_LECTERN", "RITUAL_BELL", "PRIMAL_SHOVEL", "PRIMAL_FISHING_ROD", "PRIMAL_AXE", "PRIMAL_HOE", "PRIMAL_PICKAXE").build())
            .weightFunction(ProgressiveWeightFunctionBuilder.start(3).modifier("BASIC_RITUAL", 1).modifier("EXPERT_RITUAL", 1).modifier("MASTER_RITUAL", -1).modifier("SUPREME_RITUAL", -1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RITUAL_ALTAR.get(), false).weight(10).build())
            .material(ItemMaterialBuilder.item(ItemsPM.OFFERING_PEDESTAL.get(), false).weight(5).build())
            .material(ItemMaterialBuilder.item(ItemsPM.REFINED_SALT.get(), 2, true).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RITUAL_LECTERN.get(), false).requiredResearch("RITUAL_LECTERN").weight(1).build())
            .material(ItemMaterialBuilder.item(Items.ENCHANTED_BOOK, false).requiredResearch("RITUAL_LECTERN").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RITUAL_BELL.get(), false).requiredResearch("RITUAL_BELL").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.PRIMALITE_SHOVEL.get(), true).requiredResearch("PRIMAL_SHOVEL").bonusReward(0.25D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_SHARD_EARTH.get(), true).requiredResearch("PRIMAL_SHOVEL").bonusReward(0.25D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.PRIMALITE_FISHING_ROD.get(), true).requiredResearch("PRIMAL_FISHING_ROD").bonusReward(0.25D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_SHARD_SEA.get(), true).requiredResearch("PRIMAL_FISHING_ROD").bonusReward(0.25D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.PRIMALITE_AXE.get(), true).requiredResearch("PRIMAL_AXE").bonusReward(0.25D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_SHARD_SKY.get(), true).requiredResearch("PRIMAL_AXE").bonusReward(0.25D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.PRIMALITE_HOE.get(), true).requiredResearch("PRIMAL_HOE").bonusReward(0.25D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_SHARD_SUN.get(), true).requiredResearch("PRIMAL_HOE").bonusReward(0.25D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.PRIMALITE_PICKAXE.get(), true).requiredResearch("PRIMAL_PICKAXE").bonusReward(0.25D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_SHARD_MOON.get(), true).requiredResearch("PRIMAL_PICKAXE").bonusReward(0.25D).weight(1).build())
            .build(consumer);
        ProjectBuilder.project("advanced_runework").rewardMultiplier(0.5D).requiredResearch(QuorumResearchKey.builder(3).add("RUNE_BLOOD", "RUNE_INFERNAL", "RUNE_VOID", "RUNE_ABSORB", "RUNE_DISPEL", "RUNE_SUMMON", "RUNE_AREA", "RUNE_CREATURE", "RUNE_INSIGHT").build())
            .weightFunction(ProgressiveWeightFunctionBuilder.start(3).modifier("BASIC_RUNEWORKING", 1).modifier("EXPERT_RUNEWORKING", 1).modifier("MASTER_RUNEWORKING", -1).modifier("SUPREME_RUNEWORKING", -1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RUNECARVING_TABLE.get(), false).weight(5).build())
            .material(ItemMaterialBuilder.item(Items.STONE_SLAB, 2, true).weight(3).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.GEMS_LAPIS, 2, true).weight(3).build())
            .material(ItemMaterialBuilder.item(Items.DIAMOND_SWORD, false).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RUNE_BLOOD.get(), true).requiredResearch("RUNE_BLOOD").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RUNE_INFERNAL.get(), true).requiredResearch("RUNE_INFERNAL").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RUNE_VOID.get(), true).requiredResearch("RUNE_VOID").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RUNE_INSIGHT.get(), true).requiredResearch("RUNE_INSIGHT").bonusReward(0.25D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RUNE_ABSORB.get(), true).requiredResearch("RUNE_ABSORB").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RUNE_DISPEL.get(), true).requiredResearch("RUNE_DISPEL").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RUNE_SUMMON.get(), true).requiredResearch("RUNE_SUMMON").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RUNE_AREA.get(), true).requiredResearch("RUNE_AREA").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RUNE_CREATURE.get(), true).requiredResearch("RUNE_CREATURE").weight(1).build())
            .build(consumer);
        ProjectBuilder.project("advanced_spellwork").rewardMultiplier(0.5D).requiredResearch(CompoundResearchKey.from(true, "EXPERT_SORCERY", "SHARD_SYNTHESIS"))
            .weightFunction(ProgressiveWeightFunctionBuilder.start(5).modifier("MASTER_SORCERY", -1).modifier("SUPREME_SORCERY", -1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.SPELLCRAFTING_ALTAR.get(), false).weight(5).build())
            .material(ItemMaterialBuilder.item(ItemsPM.WAND_INSCRIPTION_TABLE.get(), false).requiredResearch("WAND_INSCRIPTION").weight(2).build())
            .material(ItemMaterialBuilder.item(ItemsPM.AUTO_CHARGER.get(), false).requiredResearch("AUTO_CHARGER").weight(2).build())
            .material(ItemMaterialBuilder.item(ItemsPM.MUNDANE_WAND.get(), false).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.SPELL_SCROLL_BLANK.get(), 2, true).weight(5).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_SHARD_EARTH.get(), true).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_SHARD_SEA.get(), true).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_SHARD_SKY.get(), true).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_SHARD_SUN.get(), true).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_SHARD_MOON.get(), true).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_SHARD_BLOOD.get(), true).requiredResearch(Source.BLOOD.getDiscoverKey()).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_SHARD_INFERNAL.get(), true).requiredResearch(Source.INFERNAL.getDiscoverKey()).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_SHARD_VOID.get(), true).requiredResearch(Source.VOID.getDiscoverKey()).weight(1).build())
            .material(ObservationMaterialBuilder.observation(1, true).weight(5).build())
            .build(consumer);
        ProjectBuilder.project("advanced_wand_tinkering").rewardMultiplier(0.5D).requiredResearch("MASTER_MANAWEAVING")
            .weightFunction(ConstantWeightFunctionBuilder.weight(5).build())
            .material(ItemMaterialBuilder.item(ItemsPM.WAND_ASSEMBLY_TABLE.get(), false).requiredResearch("ADVANCED_WANDMAKING").weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.WAND_GLAMOUR_TABLE.get(), false).requiredResearch("WAND_GLAMOUR_TABLE").weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.HEARTWOOD.get(), 2, true).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.BONES, true).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.RODS_BLAZE, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.PURPUR_BLOCK, true).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(ItemTagsPM.INGOTS_PRIMALITE, true).requiredResearch("PRIMALITE").weight(1).build())
            .material(ItemTagMaterialBuilder.tag(ItemTagsPM.INGOTS_HEXIUM, true).requiredResearch("HEXIUM").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_DUST_BLOOD.get(), true).requiredResearch(Source.BLOOD.getDiscoverKey()).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_DUST_INFERNAL.get(), true).requiredResearch(Source.INFERNAL.getDiscoverKey()).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_DUST_VOID.get(), true).requiredResearch(Source.VOID.getDiscoverKey()).weight(1).build())
            .build(consumer);
        ProjectBuilder.project("apiamancy").aid(Blocks.BEEHIVE).materialCountOverride(1).baseSuccessChanceOverride(0.5D).rewardMultiplier(0.5D)
            .weightFunction(ConstantWeightFunctionBuilder.weight(5).build())
            .material(ItemTagMaterialBuilder.tag(ItemTags.SMALL_FLOWERS, true).weight(1).build())
            .otherReward(ItemRewardBuilder.item(Items.HONEYCOMB, 3).build())
            .build(consumer);
        ProjectBuilder.project("beacon_emanations").aid(Blocks.BEACON).materialCountOverride(1).baseSuccessChanceOverride(0.5D).rewardMultiplier(0.5D)
            .weightFunction(ConstantWeightFunctionBuilder.weight(5).build())
            .material(ItemTagMaterialBuilder.tag(ItemTags.BEACON_PAYMENT_ITEMS, true).weight(1).build())
            .build(consumer);
        ProjectBuilder.project("brewing_experiments").rewardMultiplier(0.5D).requiredResearch(Source.INFERNAL.getDiscoverKey())
            .weightFunction(ConstantWeightFunctionBuilder.weight(5).build())
            .material(ItemMaterialBuilder.item(Items.BREWING_STAND, false).weight(5).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.CROPS_NETHER_WART, true).weight(3).build())
            .material(ItemMaterialBuilder.item(Items.FERMENTED_SPIDER_EYE, true).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.DUSTS_GLOWSTONE, true).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.DUSTS_REDSTONE, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.SUGAR, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.RABBIT_FOOT, true).bonusReward(0.25D).weight(0.5D).build())
            .material(ItemMaterialBuilder.item(Items.BLAZE_POWDER, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.GLISTERING_MELON_SLICE, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.SPIDER_EYE, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.GHAST_TEAR, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.MAGMA_CREAM, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.PUFFERFISH, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.GOLDEN_CARROT, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.TURTLE_HELMET, true).bonusReward(0.25D).weight(0.5D).build())
            .material(ItemMaterialBuilder.item(Items.PHANTOM_MEMBRANE, true).bonusReward(0.25D).weight(0.5D).build())
            .material(ObservationMaterialBuilder.observation(1, true).weight(3).build())
            .build(consumer);
        ProjectBuilder.project("conduit_forces").aid(Blocks.CONDUIT).materialCountOverride(1).baseSuccessChanceOverride(0.5D).rewardMultiplier(0.5D)
            .weightFunction(ConstantWeightFunctionBuilder.weight(5).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.GEMS_PRISMARINE, true).weight(1).build())
            .build(consumer);
        ProjectBuilder.project("draconic_energies").aid(Blocks.DRAGON_EGG).materialCountOverride(1).baseSuccessChanceOverride(0.5D).rewardMultiplier(1.0D)
            .weightFunction(ConstantWeightFunctionBuilder.weight(5).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.ENDER_PEARLS, true).weight(1).build())
            .build(consumer);
        ProjectBuilder.project("draconic_memories").aid(Blocks.DRAGON_HEAD).aid(Blocks.DRAGON_WALL_HEAD).materialCountOverride(1).baseSuccessChanceOverride(0.5D).rewardMultiplier(0.5D)
            .weightFunction(ConstantWeightFunctionBuilder.weight(5).build())
            .material(ExperienceMaterialBuilder.experience(3, true).weight(1).build())
            .build(consumer);
        ProjectBuilder.project("enchanting_studies").requiredResearch("BASIC_MANAWEAVING")
            .weightFunction(ProgressiveWeightFunctionBuilder.start(5).modifier("EXPERT_MANAWEAVING", -1).modifier("MASTER_MANAWEAVING", -1).modifier("SUPREME_MANAWEAVING", -2).build())
            .material(ItemTagMaterialBuilder.tag(ItemTagsPM.ENCHANTING_TABLES, false).weight(5).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.GEMS_LAPIS, true).weight(5).build())
            .material(ExperienceMaterialBuilder.experience(1, true).bonusReward(0.125D).weight(5).build())
            .material(ItemMaterialBuilder.item(Items.BOOK, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.GOLDEN_SWORD, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.GOLDEN_PICKAXE, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.GOLDEN_SHOVEL, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.GOLDEN_AXE, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.GOLDEN_HOE, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.GOLDEN_HELMET, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.GOLDEN_CHESTPLATE, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.GOLDEN_LEGGINGS, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.GOLDEN_BOOTS, false).weight(1).build())
            .material(ObservationMaterialBuilder.observation(1, true).weight(5).build())
            .build(consumer);
        ProjectBuilder.project("end_expedition").requiredResearch(Source.VOID.getDiscoverKey()).rewardMultiplier(1.0D)
            .weightFunction(ConstantWeightFunctionBuilder.weight(5).build())
            .material(ItemMaterialBuilder.item(Items.NETHERITE_SWORD, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.CROSSBOW, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.ARROW, 32, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.NETHERITE_CHESTPLATE, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.MAP, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.CARTOGRAPHY_TABLE, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.TORCH, 32, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.BREAD, 8, true).weight(1).build())
            .material(ItemMaterialBuilder.item(PotionUtils.setPotion(new ItemStack(Items.POTION), Potions.SLOW_FALLING), true).bonusReward(0.5D).weight(1).matchNbt().build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.ENDER_PEARLS, 4, true).bonusReward(0.5D).weight(3).build())
            .material(ItemMaterialBuilder.item(Items.ENDER_EYE, true).weight(1).build())
            .build(consumer);
        ProjectBuilder.project("essence_analysis").requiredResearch("BASIC_ALCHEMY")
            .weightFunction(ProgressiveWeightFunctionBuilder.start(5).modifier("CRYSTAL_SYNTHESIS", -2).modifier("CLUSTER_SYNTHESIS", -2).build())
            .material(ObservationMaterialBuilder.observation(1, true).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_DUST_EARTH.get(), true).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_DUST_SEA.get(), true).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_DUST_SKY.get(), true).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_DUST_SUN.get(), true).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_DUST_MOON.get(), true).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_DUST_BLOOD.get(), true).requiredResearch(Source.BLOOD.getDiscoverKey()).afterCrafting(5).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_DUST_INFERNAL.get(), true).requiredResearch(Source.INFERNAL.getDiscoverKey()).afterCrafting(5).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_DUST_VOID.get(), true).requiredResearch(Source.VOID.getDiscoverKey()).afterCrafting(5).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_DUST_HALLOWED.get(), true).requiredResearch(Source.HALLOWED.getDiscoverKey()).afterCrafting(5).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_SHARD_EARTH.get(), true).requiredResearch(shardSynthesis).afterCrafting(5).bonusReward(0.125D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_SHARD_SEA.get(), true).requiredResearch(shardSynthesis).afterCrafting(5).bonusReward(0.125D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_SHARD_SKY.get(), true).requiredResearch(shardSynthesis).afterCrafting(5).bonusReward(0.125D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_SHARD_SUN.get(), true).requiredResearch(shardSynthesis).afterCrafting(5).bonusReward(0.125D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_SHARD_MOON.get(), true).requiredResearch(shardSynthesis).afterCrafting(5).bonusReward(0.125D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_SHARD_BLOOD.get(), true).requiredResearch(CompoundResearchKey.from(true, shardSynthesis, Source.BLOOD.getDiscoverKey())).afterCrafting(5).bonusReward(0.125D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_SHARD_INFERNAL.get(), true).requiredResearch(CompoundResearchKey.from(true, shardSynthesis, Source.INFERNAL.getDiscoverKey())).afterCrafting(5).bonusReward(0.125D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_SHARD_VOID.get(), true).requiredResearch(CompoundResearchKey.from(true, shardSynthesis, Source.VOID.getDiscoverKey())).afterCrafting(5).bonusReward(0.125D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_SHARD_HALLOWED.get(), true).requiredResearch(CompoundResearchKey.from(true, shardSynthesis, Source.HALLOWED.getDiscoverKey())).afterCrafting(5).bonusReward(0.125D).weight(1).build())
            .build(consumer);
        ProjectBuilder.project("expedition")
            .weightFunction(ProgressiveWeightFunctionBuilder.start(5).modifier(Source.INFERNAL.getDiscoverKey(), -2).modifier(Source.VOID.getDiscoverKey(), -2).build())
            .material(ItemMaterialBuilder.item(Items.IRON_SWORD, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.BOW, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.ARROW, 4, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.IRON_CHESTPLATE, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.MAP, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.COMPASS, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.CLOCK, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.CARTOGRAPHY_TABLE, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.CAMPFIRE, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.TORCH, 4, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.BREAD, true).weight(1).build())
            .build(consumer);
        ProjectBuilder.project("hit_the_books").aid(Blocks.BOOKSHELF).materialCountOverride(1).baseSuccessChanceOverride(0.5D).rewardMultiplier(0.5D)
            .weightFunction(ConstantWeightFunctionBuilder.weight(5).build())
            .material(ItemMaterialBuilder.item(Items.BOOK, false).weight(1).build())
            .otherReward(ExperienceRewardBuilder.points(5).build())
            .build(consumer);
        ProjectBuilder.project("magitech_tinkering").rewardMultiplier(0.5D).requiredResearch(QuorumResearchKey.builder(3).add("ARCANOMETER", "CONCOCTING_TINCTURES", "ENTROPY_SINK", "AUTO_CHARGER", "ESSENCE_TRANSMUTER", "DISSOLUTION_CHAMBER", "INFERNAL_FURNACE").build())
            .weightFunction(ProgressiveWeightFunctionBuilder.start(3).modifier("MASTER_MAGITECH", 2).build())
            .material(ItemMaterialBuilder.item(ItemsPM.MAGITECH_PARTS_BASIC.get(), true).bonusReward(0.125D).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.MAGITECH_PARTS_ENCHANTED.get(), true).requiredResearch("EXPERT_MAGITECH").bonusReward(0.25D).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.MAGITECH_PARTS_FORBIDDEN.get(), true).requiredResearch("MASTER_MAGITECH").bonusReward(0.5D).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.HONEY_EXTRACTOR.get(), false).requiredResearch("HONEY_EXTRACTOR").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ARCANOMETER.get(), false).requiredResearch("ARCANOMETER").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.CONCOCTER.get(), false).requiredResearch("CONCOCTING_TINCTURES").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ENTROPY_SINK.get(), false).requiredResearch("ENTROPY_SINK").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.AUTO_CHARGER.get(), false).requiredResearch("AUTO_CHARGER").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_TRANSMUTER.get(), false).requiredResearch("ESSENCE_TRANSMUTER").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.DISSOLUTION_CHAMBER.get(), false).requiredResearch("DISSOLUTION_CHAMBER").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.INFERNAL_FURNACE.get(), false).requiredResearch("INFERNAL_FURNACE").weight(1).build())
            .build(consumer);
        ProjectBuilder.project("master_enchanting_studies").rewardMultiplier(1D).requiredResearch(CompoundResearchKey.from(true, "MASTER_MANAWEAVING", "HEXIUM"))
            .weightFunction(ConstantWeightFunctionBuilder.weight(5).build())
            .material(ItemTagMaterialBuilder.tag(ItemTagsPM.ENCHANTING_TABLES, false).weight(5).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.GEMS_LAPIS, 3, true).weight(5).build())
            .material(ExperienceMaterialBuilder.experience(3, true).bonusReward(0.5D).weight(5).build())
            .material(ItemMaterialBuilder.item(Items.BOOK, false).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.HEXIUM_SWORD.get(), false).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.HEXIUM_PICKAXE.get(), false).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.HEXIUM_SHOVEL.get(), false).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.HEXIUM_AXE.get(), false).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.HEXIUM_HOE.get(), false).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.HEXIUM_HEAD.get(), false).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.HEXIUM_CHEST.get(), false).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.HEXIUM_LEGS.get(), false).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.HEXIUM_FEET.get(), false).weight(1).build())
            .material(ObservationMaterialBuilder.observation(1, true).weight(5).build())
            .build(consumer);
        ProjectBuilder.project("master_essence_analysis").requiredResearch("CLUSTER_SYNTHESIS").rewardMultiplier(1.0D)
            .weightFunction(ConstantWeightFunctionBuilder.weight(5).build())
            .material(ObservationMaterialBuilder.observation(1, true).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CRYSTAL_EARTH.get(), true).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CRYSTAL_SEA.get(), true).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CRYSTAL_SKY.get(), true).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CRYSTAL_SUN.get(), true).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CRYSTAL_MOON.get(), true).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CRYSTAL_BLOOD.get(), true).requiredResearch(Source.BLOOD.getDiscoverKey()).afterCrafting(5).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CRYSTAL_INFERNAL.get(), true).requiredResearch(Source.INFERNAL.getDiscoverKey()).afterCrafting(5).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CRYSTAL_VOID.get(), true).requiredResearch(Source.VOID.getDiscoverKey()).afterCrafting(5).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CRYSTAL_HALLOWED.get(), true).requiredResearch(Source.HALLOWED.getDiscoverKey()).afterCrafting(5).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CLUSTER_EARTH.get(), true).afterCrafting(5).bonusReward(0.5D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CLUSTER_SEA.get(), true).afterCrafting(5).bonusReward(0.5D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CLUSTER_SKY.get(), true).afterCrafting(5).bonusReward(0.5D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CLUSTER_SUN.get(), true).afterCrafting(5).bonusReward(0.5D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CLUSTER_MOON.get(), true).afterCrafting(5).bonusReward(0.5D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CLUSTER_BLOOD.get(), true).requiredResearch(Source.BLOOD.getDiscoverKey()).afterCrafting(5).bonusReward(0.5D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CLUSTER_INFERNAL.get(), true).requiredResearch(Source.INFERNAL.getDiscoverKey()).afterCrafting(5).bonusReward(0.5D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CLUSTER_VOID.get(), true).requiredResearch(Source.VOID.getDiscoverKey()).afterCrafting(5).weight(1).bonusReward(0.5D).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CLUSTER_HALLOWED.get(), true).requiredResearch(Source.HALLOWED.getDiscoverKey()).afterCrafting(5).bonusReward(0.5D).weight(1).build())
            .build(consumer);
        ProjectBuilder.project("master_ritual_practice").rewardMultiplier(1D).requiredResearch(QuorumResearchKey.builder(2).add("BLOODLETTER", "SOUL_ANVIL", "FORBIDDEN_TRIDENT", "FORBIDDEN_SWORD", "FORBIDDEN_BOW").build())
            .weightFunction(ConstantWeightFunctionBuilder.weight(5).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RITUAL_ALTAR.get(), false).weight(10).build())
            .material(ItemMaterialBuilder.item(ItemsPM.OFFERING_PEDESTAL.get(), false).weight(5).build())
            .material(ItemMaterialBuilder.item(ItemsPM.REFINED_SALT.get(), 4, true).weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.BLOODLETTER.get(), false).requiredResearch("BLOODLETTER").weight(1).build())
            .material(ItemMaterialBuilder.item(Items.WATER_BUCKET, true).requiredResearch("BLOODLETTER").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.SOUL_ANVIL.get(), false).requiredResearch("SOUL_ANVIL").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.SPELLCLOTH.get(), false).requiredResearch("SOUL_ANVIL").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.HEXIUM_TRIDENT.get(), true).requiredResearch("FORBIDDEN_TRIDENT").bonusReward(0.5D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_SHARD_BLOOD.get(), true).requiredResearch("FORBIDDEN_TRIDENT").bonusReward(0.5D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.HEXIUM_BOW.get(), true).requiredResearch("FORBIDDEN_BOW").bonusReward(0.5D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_SHARD_INFERNAL.get(), true).requiredResearch("FORBIDDEN_BOW").bonusReward(0.5D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.HEXIUM_SWORD.get(), true).requiredResearch("FORBIDDEN_SWORD").bonusReward(0.5D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_SHARD_VOID.get(), true).requiredResearch("FORBIDDEN_SWORD").bonusReward(0.5D).weight(1).build())
            .build(consumer);
        ProjectBuilder.project("master_runework").rewardMultiplier(1D).requiredResearch("RUNE_HALLOWED")
            .weightFunction(ConstantWeightFunctionBuilder.weight(5).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RUNECARVING_TABLE.get(), false).weight(5).build())
            .material(ItemMaterialBuilder.item(Items.STONE_SLAB, 4, true).weight(3).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.GEMS_LAPIS, 4, true).weight(3).build())
            .material(ItemMaterialBuilder.item(Items.DIAMOND_SWORD, false).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RUNE_HALLOWED.get(), true).requiredResearch("RUNE_HALLOWED").weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RUNE_POWER.get(), true).requiredResearch("RUNE_POWER").bonusReward(0.5D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RUNE_PROJECT.get(), 2, true).requiredResearch("RUNE_PROJECT").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RUNE_PROTECT.get(), 2, true).requiredResearch("RUNE_PROTECT").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RUNE_ITEM.get(), 2, true).requiredResearch("RUNE_ITEM").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RUNE_SELF.get(), 2, true).requiredResearch("RUNE_SELF").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RUNE_ABSORB.get(), 2, true).requiredResearch("RUNE_ABSORB").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RUNE_DISPEL.get(), 2, true).requiredResearch("RUNE_DISPEL").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RUNE_SUMMON.get(), 2, true).requiredResearch("RUNE_SUMMON").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RUNE_AREA.get(), 2, true).requiredResearch("RUNE_AREA").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RUNE_CREATURE.get(), 2, true).requiredResearch("RUNE_CREATURE").weight(1).build())
            .build(consumer);
        ProjectBuilder.project("master_spellwork").rewardMultiplier(1D).requiredResearch(CompoundResearchKey.from(true, "MASTER_SORCERY", "CRYSTAL_SYNTHESIS"))
            .weightFunction(ConstantWeightFunctionBuilder.weight(5).build())
            .material(ItemMaterialBuilder.item(ItemsPM.SPELLCRAFTING_ALTAR.get(), false).weight(5).build())
            .material(ItemMaterialBuilder.item(ItemsPM.WAND_INSCRIPTION_TABLE.get(), false).requiredResearch("WAND_INSCRIPTION").weight(2).build())
            .material(ItemMaterialBuilder.item(ItemsPM.MANA_NEXUS.get(), false).requiredResearch("MANA_NEXUS").weight(2).build())
            .material(ItemMaterialBuilder.item(ItemsPM.SPELL_SCROLL_BLANK.get(), 4, true).weight(5).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CRYSTAL_EARTH.get(), true).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CRYSTAL_SEA.get(), true).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CRYSTAL_SKY.get(), true).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CRYSTAL_SUN.get(), true).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CRYSTAL_MOON.get(), true).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CRYSTAL_BLOOD.get(), true).requiredResearch(Source.BLOOD.getDiscoverKey()).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CRYSTAL_INFERNAL.get(), true).requiredResearch(Source.INFERNAL.getDiscoverKey()).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_CRYSTAL_VOID.get(), true).requiredResearch(Source.VOID.getDiscoverKey()).weight(1).build())
            .material(ObservationMaterialBuilder.observation(1, true).weight(5).build())
            .build(consumer);
        ProjectBuilder.project("mundane_tinkering")
            .weightFunction(ProgressiveWeightFunctionBuilder.start(5).modifier("BASIC_MAGITECH", -1).modifier("EXPERT_MAGITECH", -1).modifier("MASTER_MAGITECH", -1).modifier("SUPREME_MAGITECH", -1).build())
            .material(ItemMaterialBuilder.item(Items.CRAFTING_TABLE, false).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(ItemTags.ANVIL, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.FURNACE, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.BLAST_FURNACE, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.LOOM, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.SMOKER, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.SMITHING_TABLE, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.STONECUTTER, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.GRINDSTONE, false).weight(1).build())
            .material(ObservationMaterialBuilder.observation(1, true).weight(5).build())
            .build(consumer);
        ProjectBuilder.project("nether_expedition").requiredResearch(Source.INFERNAL.getDiscoverKey()).rewardMultiplier(0.5D)
            .weightFunction(ProgressiveWeightFunctionBuilder.start(5).modifier(Source.VOID.getDiscoverKey(), -2).build())
            .material(ItemMaterialBuilder.item(Items.DIAMOND_SWORD, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.CROSSBOW, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.ARROW, 16, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.DIAMOND_CHESTPLATE, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.MAP, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.CARTOGRAPHY_TABLE, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.TORCH, 16, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.BREAD, 4, true).weight(1).build())
            .material(ItemMaterialBuilder.item(PotionUtils.setPotion(new ItemStack(Items.POTION), Potions.FIRE_RESISTANCE), true).bonusReward(0.25D).weight(4).matchNbt().build())
            .material(ItemTagMaterialBuilder.tag(ItemTagsForgeExt.MILK, true).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.OBSIDIAN, 10, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.FLINT_AND_STEEL, false).weight(1).build())
            .build(consumer);
        ProjectBuilder.project("observation_analysis").aid(BlocksPM.ANALYSIS_TABLE.get()).materialCountOverride(1).baseSuccessChanceOverride(0.5D).rewardMultiplier(0.5D)
            .weightFunction(ConstantWeightFunctionBuilder.weight(5).build())
            .material(ObservationMaterialBuilder.observation(1, true).weight(1).build())
            .build(consumer);
        ProjectBuilder.project("piglin_barter").requiredResearch(Source.INFERNAL.getDiscoverKey()).rewardMultiplier(1D)
            .weightFunction(ConstantWeightFunctionBuilder.weight(5).build())
            .material(ItemMaterialBuilder.item(Items.BELL, true).weight(0.5D).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.STORAGE_BLOCKS_GOLD, true).bonusReward(0.5D).weight(0.5D).build())
            .material(ItemMaterialBuilder.item(Items.RAW_GOLD_BLOCK, true).bonusReward(0.5D).weight(0.5D).build())
            .material(ItemMaterialBuilder.item(Items.CLOCK, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.GILDED_BLACKSTONE, true).weight(2).build())
            .material(ItemMaterialBuilder.item(Items.GLISTERING_MELON_SLICE, true).weight(2).build())
            .material(ItemMaterialBuilder.item(Items.RAW_GOLD, true).weight(2).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.INGOTS_GOLD, true).weight(5).build())
            .material(ItemMaterialBuilder.item(Items.GOLDEN_APPLE, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.GOLDEN_AXE, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.GOLDEN_BOOTS, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.GOLDEN_CARROT, true).weight(2).build())
            .material(ItemMaterialBuilder.item(Items.GOLDEN_CHESTPLATE, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.GOLDEN_HELMET, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.GOLDEN_HOE, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.GOLDEN_HORSE_ARMOR, true).bonusReward(0.5D).weight(0.5D).build())
            .material(ItemMaterialBuilder.item(Items.GOLDEN_LEGGINGS, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.GOLDEN_PICKAXE, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.GOLDEN_SHOVEL, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.GOLDEN_SWORD, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.LIGHT_WEIGHTED_PRESSURE_PLATE, true).weight(1).build())
            .otherReward(LootTableRewardBuilder.table(new ResourceLocation("gameplay/piglin_bartering"), "label.primalmagick.loot_table.piglin_bartering.desc").build())
            .build(consumer);
        ProjectBuilder.project("portal_detritus").aid(Blocks.NETHER_PORTAL).materialCountOverride(1).baseSuccessChanceOverride(0.5D).rewardMultiplier(0.5D)
            .weightFunction(ConstantWeightFunctionBuilder.weight(5).build())
            .material(ItemMaterialBuilder.item(ItemsPM.MAGNIFYING_GLASS.get(), false).weight(1).build())
            .build(consumer);
        ProjectBuilder.project("prosperous_trade").rewardMultiplier(0.5D).requiredResearch(Source.INFERNAL.getDiscoverKey())
            .weightFunction(ProgressiveWeightFunctionBuilder.start(5).modifier(Source.VOID.getDiscoverKey(), -2).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.GEMS_EMERALD, 2, true).bonusReward(0.5D).weight(2).build())
            .material(ItemMaterialBuilder.item(Items.LAVA_BUCKET, true).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.GEMS_DIAMOND, true).bonusReward(0.25D).weight(3).build())
            .material(ItemMaterialBuilder.item(Items.COAL, 2, true).weight(2).build())
            .material(ItemMaterialBuilder.item(Items.MUTTON, 2, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.BEEF, 2, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.COMPASS, true).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.INGOTS_GOLD, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.GLOWSTONE, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.MELON, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.CAKE, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.SALMON, 2, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.TROPICAL_FISH, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.FLINT, 3, true).weight(3).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.FEATHERS, 3, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.RABBIT_HIDE, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.INK_SAC, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.WRITABLE_BOOK, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.GRANITE, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.ANDESITE, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.DIORITE, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.SHEARS, true).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(ItemTags.BEDS, true).weight(1).build())
            .otherReward(LootTableRewardBuilder.table(PrimalMagick.resource("gameplay/theorycrafting/prosperous_trade"), "label.primalmagick.loot_table.prosperous_trade.desc").build())
            .build(consumer);
        ProjectBuilder.project("raiding_the_raiders").rewardMultiplier(0.5D)
            .weightFunction(ConstantWeightFunctionBuilder.weight(5).build())
            .material(ItemMaterialBuilder.item(Raid.getLeaderBannerInstance(), true).matchNbt().bonusReward(0.25D).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.BLOODY_FLESH.get(), true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.CROSSBOW, true).weight(3).build())
            .material(ItemMaterialBuilder.item(Items.IRON_SWORD, true).weight(3).build())
            .material(ItemMaterialBuilder.item(Items.IRON_AXE, true).weight(3).build())
            .material(ItemMaterialBuilder.item(Items.ARROW, 4, true).weight(3).build())
            .material(ItemMaterialBuilder.item(Items.GLASS_BOTTLE, 3, true).weight(3).build())
            .material(ItemMaterialBuilder.item(Items.DARK_OAK_LOG, 16, true).weight(3).build())
            .material(ItemMaterialBuilder.item(Items.CARVED_PUMPKIN, true).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.GEMS_EMERALD, true).bonusReward(0.25D).weight(1).build())
            .build(consumer);
        ProjectBuilder.project("recuperation")
            .weightFunction(ProgressiveWeightFunctionBuilder.start(5).modifier(Source.INFERNAL.getDiscoverKey(), -2).modifier(Source.VOID.getDiscoverKey(), -2).build())
            .material(ItemTagMaterialBuilder.tag(ItemTags.BEDS, false).weight(2).build())
            .material(ItemMaterialBuilder.item(Items.JUKEBOX, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.BOOK, false).weight(2).build())
            .material(ItemTagMaterialBuilder.tag(ItemTagsPM.FOOD_COOKED_BEEF, true).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(ItemTagsPM.FOOD_BAKED_POTATO, true).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(ItemTagsForgeExt.MILK, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.CAKE, true).bonusReward(0.125D).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.ROSE_BUSH, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.TNT, true).bonusReward(0.125D).weight(0.5D).build())
            .build(consumer);
        ProjectBuilder.project("redstone_tinkering").requiredResearch("BASIC_MAGITECH")
            .weightFunction(ProgressiveWeightFunctionBuilder.start(5).modifier("BASIC_MAGITECH", -1).modifier("EXPERT_MAGITECH", -1).modifier("MASTER_MAGITECH", -1).modifier("SUPREME_MAGITECH", -1).build())
            .material(ItemMaterialBuilder.item(Items.DETECTOR_RAIL, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.ACTIVATOR_RAIL, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.DISPENSER, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.DROPPER, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.DAYLIGHT_DETECTOR, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.PISTON, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.HOPPER, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.REDSTONE_LAMP, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.STICKY_PISTON, false).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.COMPARATOR, false).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.DUSTS_REDSTONE, 4, true).weight(3).build())
            .material(ObservationMaterialBuilder.observation(1, true).weight(5).build())
            .build(consumer);
        ProjectBuilder.project("rich_trade").rewardMultiplier(1D).requiredResearch(Source.VOID.getDiscoverKey())
            .weightFunction(ConstantWeightFunctionBuilder.weight(5).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.GEMS_EMERALD, 4, true).bonusReward(1D).weight(2).build())
            .material(ItemMaterialBuilder.item(Items.SHIELD, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.DIAMOND_CHESTPLATE, true).bonusReward(0.5D).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.DRIED_KELP_BLOCK, 2, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.SWEET_BERRIES, 4, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.ITEM_FRAME, true).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(ItemTags.BANNERS, true).weight(2).build())
            .material(ItemMaterialBuilder.item(Items.GLASS_BOTTLE, 3, true).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.CROPS_NETHER_WART, 4, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.GOLDEN_CARROT, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.GLISTERING_MELON_SLICE, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.PUFFERFISH, true).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(ItemTags.BOATS, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.TRIPWIRE_HOOK, 2, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.CROSSBOW, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.LEATHER_HORSE_ARMOR, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.SADDLE, true).bonusReward(0.5D).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.CLOCK, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.NAME_TAG, true).bonusReward(0.5D).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.GEMS_QUARTZ, 2, true).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(ItemTags.TERRACOTTA, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.PAINTING, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.DIAMOND_AXE, true).bonusReward(0.25D).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.DIAMOND_PICKAXE, true).bonusReward(0.25D).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.DIAMOND_SWORD, true).bonusReward(0.25D).weight(1).build())
            .otherReward(LootTableRewardBuilder.table(PrimalMagick.resource("gameplay/theorycrafting/rich_trade"), "label.primalmagick.loot_table.rich_trade.desc").build())
            .build(consumer);
        ProjectBuilder.project("ritual_practice").requiredResearch(QuorumResearchKey.builder(2).add("MANAFRUIT", "RITUAL_CANDLES", "INCENSE_BRAZIER", "DOWSING_ROD").build())
            .weightFunction(ProgressiveWeightFunctionBuilder.start(5).modifier("EXPERT_RITUAL", -1).modifier("MASTER_RITUAL", -1).modifier("SUPREME_RITUAL", -2).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RITUAL_ALTAR.get(), false).weight(10).build())
            .material(ItemMaterialBuilder.item(ItemsPM.OFFERING_PEDESTAL.get(), false).weight(5).build())
            .material(ItemMaterialBuilder.item(ItemsPM.REFINED_SALT.get(), true).weight(3).build())
            .material(ItemMaterialBuilder.item(Items.APPLE, true).requiredResearch("MANAFRUIT").weight(1).bonusReward(0.125D).build())
            .material(ItemMaterialBuilder.item(Items.HONEY_BOTTLE, true).requiredResearch("MANAFRUIT").weight(1).bonusReward(0.125D).build())
            .material(ItemMaterialBuilder.item(ItemsPM.MANA_SALTS.get(), true).requiredResearch("MANAFRUIT").weight(1).bonusReward(0.125D).build())
            .material(ItemTagMaterialBuilder.tag(ItemTagsPM.RITUAL_CANDLES, false).requiredResearch("RITUAL_CANDLES").weight(1).build())
            .material(ItemMaterialBuilder.item(Items.FLINT_AND_STEEL, false).requiredResearch("RITUAL_CANDLES").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.INCENSE_BRAZIER.get(), false).requiredResearch("INCENSE_BRAZIER").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.INCENSE_STICK.get(), true).requiredResearch("INCENSE_BRAZIER").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.DOWSING_ROD.get(), false).requiredResearch("DOWSING_ROD").weight(1).build())
            .build(consumer);
        ProjectBuilder.project("runework").requiredResearch(QuorumResearchKey.builder(3).add("RUNE_EARTH", "RUNE_SEA", "RUNE_SKY", "RUNE_SUN", "RUNE_MOON", "RUNE_PROJECT", "RUNE_PROTECT", "RUNE_ITEM", "RUNE_SELF").build())
            .weightFunction(ProgressiveWeightFunctionBuilder.start(5).modifier("EXPERT_RUNEWORKING", -1).modifier("MASTER_RUNEWORKING", -1).modifier("SUPREME_RUNEWORKING", -2).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RUNECARVING_TABLE.get(), false).weight(5).build())
            .material(ItemMaterialBuilder.item(Items.STONE_SLAB, true).weight(3).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.GEMS_LAPIS, true).weight(3).build())
            .material(ItemMaterialBuilder.item(Items.DIAMOND_SWORD, false).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RUNE_EARTH.get(), true).requiredResearch("RUNE_EARTH").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RUNE_SEA.get(), true).requiredResearch("RUNE_SEA").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RUNE_SKY.get(), true).requiredResearch("RUNE_SKY").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RUNE_SUN.get(), true).requiredResearch("RUNE_SUN").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RUNE_MOON.get(), true).requiredResearch("RUNE_MOON").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RUNE_PROJECT.get(), true).requiredResearch("RUNE_PROJECT").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RUNE_PROTECT.get(), true).requiredResearch("RUNE_PROTECT").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RUNE_ITEM.get(), true).requiredResearch("RUNE_ITEM").weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.RUNE_SELF.get(), true).requiredResearch("RUNE_SELF").weight(1).build())
            .build(consumer);
        ProjectBuilder.project("spellwork").requiredResearch("BASIC_SORCERY")
            .weightFunction(ProgressiveWeightFunctionBuilder.start(5).modifier("EXPERT_SORCERY", -1).modifier("MASTER_SORCERY", -1).modifier("SUPREME_SORCERY", -2).build())
            .material(ItemMaterialBuilder.item(ItemsPM.SPELLCRAFTING_ALTAR.get(), false).weight(5).build())
            .material(ItemMaterialBuilder.item(ItemsPM.WAND_INSCRIPTION_TABLE.get(), false).requiredResearch("WAND_INSCRIPTION").weight(2).build())
            .material(ItemMaterialBuilder.item(ItemsPM.WAND_CHARGER.get(), false).requiredResearch("WAND_CHARGER").weight(2).build())
            .material(ItemMaterialBuilder.item(ItemsPM.MUNDANE_WAND.get(), false).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.SPELL_SCROLL_BLANK.get(), true).weight(5).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_DUST_EARTH.get(), true).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_DUST_SEA.get(), true).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_DUST_SKY.get(), true).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_DUST_SUN.get(), true).weight(1).build())
            .material(ItemMaterialBuilder.item(ItemsPM.ESSENCE_DUST_MOON.get(), true).weight(1).build())
            .material(ObservationMaterialBuilder.observation(1, true).weight(5).build())
            .build(consumer);
        ProjectBuilder.project("trade")
            .weightFunction(ProgressiveWeightFunctionBuilder.start(5).modifier(Source.INFERNAL.getDiscoverKey(), -2).modifier(Source.VOID.getDiscoverKey(), -2).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.GEMS_EMERALD, true).bonusReward(0.25D).weight(2).build())
            .material(ItemMaterialBuilder.item(Items.COAL, 2, true).weight(3).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.INGOTS_IRON, true).weight(3).build())
            .material(ItemMaterialBuilder.item(Items.CHICKEN, 2, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.PORKCHOP, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.PAPER, 4, true).weight(2).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.GLASS_PANES, 2, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.ROTTEN_FLESH, 4, true).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.CROPS_WHEAT, 3, true).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.CROPS_POTATO, 3, true).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.CROPS_CARROT, 3, true).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.CROPS_BEETROOT, 3, true).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.STRING, 3, true).weight(2).build())
            .material(ItemMaterialBuilder.item(Items.COD, 2, true).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.RODS_WOODEN, 4, true).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.LEATHER, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.BOOK, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.CLAY_BALL, 2, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.STONE, 2, true).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(ItemTags.WOOL, 2, true).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.DYES, 2, true).weight(1).build())
            .otherReward(LootTableRewardBuilder.table(PrimalMagick.resource("gameplay/theorycrafting/trade"), "label.primalmagick.loot_table.trade.desc").build())
            .build(consumer);
        ProjectBuilder.project("wand_tinkering").requiredResearch("BASIC_MANAWEAVING")
            .weightFunction(ProgressiveWeightFunctionBuilder.start(5).modifier("MASTER_MANAWEAVING", -2).build())
            .material(ItemMaterialBuilder.item(ItemsPM.WAND_ASSEMBLY_TABLE.get(), false).requiredResearch("ADVANCED_WANDMAKING").weight(3).build())
            .material(ItemMaterialBuilder.item(ItemsPM.HEARTWOOD.get(), true).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.OBSIDIAN, true).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(ItemTagsPM.CORAL_BLOCKS, true).weight(1).build())
            .material(ItemMaterialBuilder.item(Items.BAMBOO, true).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(ItemTagsPM.SUNWOOD_LOGS, true).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(ItemTagsPM.MOONWOOD_LOGS, true).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.INGOTS_IRON, true).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.INGOTS_GOLD, true).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(Tags.Items.GEMS_DIAMOND, true).weight(1).build())
            .material(ItemTagMaterialBuilder.tag(ItemTagsPM.ESSENCES_TERRESTRIAL_DUSTS, true).weight(1).build())
            .material(ObservationMaterialBuilder.observation(1, true).weight(5).build())
            .build(consumer);
    }

    @Override
    public String getName() {
        return "Primal Magick Theorycrafting Projects";
    }
}
